(:xs (((:name . 1) (:day . "monday"))
      ((:name . 2) (:day . "monday"))
      ((:name . 3) (:day . "monday"))
      ((:name . 4) (:day . "tuesday"))
      ((:name . 5) (:day . "tuesday"))
      ((:name . 6) (:day . "tuesday"))
      ((:name . 7) (:day . "wednesday"))
      ((:name . 9) (:day . "wednesday"))
      ((:name . 10) (:day . "wednesday"))))
